export const ingredients = [
  { name: "Abats" },
  { name: "Abricot" },
  { name: "Abricots secs" },
  { name: "Abricots secs dénoyautés" },
  { name: "Absinthe" },
  { name: "Acai berry" },
  { name: "Achillée millefeuille" },
  { name: "Acide pantothénique" },
  { name: "Acidifiant" },
  { name: "Acérola" },
  { name: "Amande" },
  { name: "Amande amère" },
  { name: "Amande douce" },
  { name: "Amande en poudre" },
  { name: "Amande émondée" },
  { name: "Amandes" },
  { name: "Amandes entières" },
  { name: "Amandes grillées" },
  { name: "Amaretto" },
  { name: "Ananas" },
  { name: "Anchois" },
  { name: "Aneth" },
  { name: "Anis" },
  { name: "Armagnac" },
  { name: "Artichaut" },
  { name: "Asperge" },
  { name: "Aubergine" },
  { name: "Avocat" },
  { name: "Avoine" },
  { name: "Babeurre" },
  { name: "Bacon" },
  { name: "Bananes" },
  { name: "Basilic" },
  { name: "Betterave" },
  { name: "Beurre" },
  { name: "Beurre clarifié" },
  { name: "Beurre doux" },
  { name: "Beurre salé" },
  { name: "Bière" },
  { name: "Blanc d'œuf" },
  { name: "Blé" },
  { name: "Blé complet" },
  { name: "Boeuf" },
  { name: "Brocoli" },
  { name: "Cacahuète" },
  { name: "Cacao" },
  { name: "Café" },
  { name: "Camembert" },
  { name: "Canard" },
  { name: "Cannelle" },
  { name: "Carotte" },
  { name: "Cassis" },
  { name: "Cerise" },
  { name: "Champagne" },
  { name: "Champignon" },
  { name: "Chocolat" },
  { name: "Chou" },
  { name: "Chou-fleur" },
  { name: "Cidre" },
  { name: "Clémentine" },
  { name: "Cognac" },
  { name: "Coing" },
  { name: "Cola" },
  { name: "Concombre" },
  { name: "Courgette" },
  { name: "Crabe" },
  { name: "Crevette" },
  { name: "Crème de cacao" },
  { name: "Crème de menthe" },
  { name: "Cumin" },
  { name: "Curcuma" },
  { name: "Céleri" },
  { name: "Dinde" },
  { name: "Eau" },
  { name: "Eau de coco" },
  { name: "Epinard" },
  { name: "Farine" },
  { name: "Fenouil" },
  { name: "Figue" },
  { name: "Filet de poulet" },
  { name: "Fraise" },
  { name: "Framboise" },
  { name: "Fromage" },
  { name: "Fécule de maïs" },
  { name: "Gin" },
  { name: "Gingembre" },
  { name: "Ginger ale" },
  { name: "Ginger beer" },
  { name: "Haricot" },
  { name: "Huile d'olive" },
  { name: "Huile de colza" },
  { name: "Huile de tournesol" },
  { name: "Jambon" },
  { name: "Jaune d'œuf" },
  { name: "Jus d'ananas" },
  { name: "Jus d'orange" },
  { name: "Jus de citron" },
  { name: "Jus de cranberry" },
  { name: "Jus de pamplemousse" },
  { name: "Jus de pomme" },
  { name: "Jus de raisin" },
  { name: "Jus de tomate" },
  { name: "Kiwi" },
  { name: "Kombucha" },
  { name: "Lait" },
  { name: "Lentille" },
  { name: "Lette" },
  { name: "Lime" },
  { name: "Liqueur d'orange" },
  { name: "Liqueur de cassis" },
  { name: "Mangue" },
  { name: "Maté" },
  { name: "Maïs" },
  { name: "Melon" },
  { name: "Menthe" },
  { name: "Miel" },
  { name: "Moutarde" },
  { name: "Mytille" },
  { name: "Navet" },
  { name: "Nectar de goyave" },
  { name: "Nectar de mangue" },
  { name: "Noisette" },
  { name: "Noix" },
  { name: "Oeuf" },
  { name: "Oignon" },
  { name: "Orange" },
  { name: "Orge" },
  { name: "Pamplemousse" },
  { name: "Papaye" },
  { name: "Paprika" },
  { name: "Pastis" },
  { name: "Persil" },
  { name: "Petit pois" },
  { name: "Poire" },
  { name: "Poireau" },
  { name: "Pois chiche" },
  { name: "Poivre" },
  { name: "Poivron" },
  { name: "Pomme" },
  { name: "Porc" },
  { name: "Pâtes" },
  { name: "Pêche" },
  { name: "Quinoa" },
  { name: "Raisin" },
  { name: "Raisin sec" },
  { name: "Rhum" },
  { name: "Riz" },
  { name: "Romarin" },
  { name: "Roquette" },
  { name: "Rose" },
  { name: "Saké" },
  { name: "Salade" },
  { name: "Salsifis" },
  { name: "Saumon" },
  { name: "Seigle" },
  { name: "Sel" },
  { name: "Sirop d'orgeat" },
  { name: "Sirop de grenadine" },
  { name: "Sirop de menthe" },
  { name: "Sirop de sucre" },
  { name: "Soda" },
  { name: "Soja" },
  { name: "Sucre" },
  { name: "Tapioca" },
  { name: "Tequila" },
  { name: "Thon" },
  { name: "Thé" },
  { name: "Thé glacé" },
  { name: "Tomate" },
  { name: "Tonic" },
  { name: "Triple sec" },
  { name: "Truite" },
  { name: "Vanille" },
  { name: "Veau" },
  { name: "Viande" },
  { name: "Vin blanc" },
  { name: "Vin rosé" },
  { name: "Vin rouge" },
  { name: "Vinaigre" },
  { name: "Vodka" },
  { name: "Whisky" },
  { name: "Yaourt" },
];
