export const ingredients = [
  { name: "Abats" },
  { name: "Abondance" },
  { name: "Abricot" },
  { name: "Abricots secs" },
  { name: "Abricots secs dénoyautés" },
  { name: "Absinthe" },
  { name: "Acai berry" },
  { name: "Achillée millefeuille" },
  { name: "Acide pantothénique" },
  { name: "Acidifiant" },
  { name: "Acérola" },
  { name: "Agar agar" },
  { name: "Agneau" },
  { name: "Amande" },
  { name: "Amande amère" },
  { name: "Amande douce" },
  { name: "Amande en poudre" },
  { name: "Amande émondée" },
  { name: "Amandes" },
  { name: "Amandes entières" },
  { name: "Amandes grillées" },
  { name: "Amaretto" },
  { name: "Ananas" },
  { name: "Anchois" },
  { name: "Andouillette" },
  { name: "Aneth" },
  { name: "Anguille" },
  { name: "Anis" },
  { name: "Anis étoilé" },
  { name: "Apérol" },
  { name: "Armagnac" },
  { name: "Artichaut" },
  { name: "Asperge" },
  { name: "Aubergine" },
  { name: "Avocat" },
  { name: "Avoine" },
  { name: "Babeurre" },
  { name: "Bacon" },
  { name: "Badiane" },
  { name: "Baguette" },
  { name: "Baies d'açaï" },
  { name: "Baileys" },
  { name: "Bananes" },
  { name: "Bar" },
  { name: "Basilic" },
  { name: "Betterave" },
  { name: "Betterave chioggia" },
  { name: "Beurre" },
  { name: "Beurre clarifié" },
  { name: "Beurre doux" },
  { name: "Beurre salé" },
  { name: "Bicarbonate de soude" },
  { name: "Bière" },
  { name: "Bière blanche" },
  { name: "Bière blonde" },
  { name: "Bière brune" },
  { name: "Blanc d'œuf" },
  { name: "Blé" },
  { name: "Blé complet" },
  { name: "Boeuf" },
  { name: "Boudin noir" },
  { name: "Boursin" },
  { name: "Brocoli" },
  { name: "Cacao" },
  { name: "Cachaça" },
  { name: "Café" },
  { name: "Calvados" },
  { name: "Camerise" },
  { name: "Camembert" },
  { name: "Canard" },
  { name: "Cannelle" },
  { name: "Cantal" },
  { name: "Cardamome" },
  { name: "Cardon" },
  { name: "Carotte" },
  { name: "Cassis" },
  { name: "Céleri" },
  { name: "Céleri en poudre" },
  { name: "Cerfeuil" },
  { name: "Cerise" },
  { name: "Cervelas" },
  { name: "Chapati" },
  { name: "Champagne" },
  { name: "Champagne rosé" },
  { name: "Champignon" },
  { name: "Chanterelle" },
  { name: "Chapelure" },
  { name: "Charcuterie" },
  { name: "Chèvre" },
  { name: "Cheddar" },
  { name: "Chili" },
  { name: "Chocolat" },
  { name: "Chorizo" },
  { name: "Chou" },
  { name: "Chou chinois" },
  { name: "Chou kale" },
  { name: "Chou rouge" },
  { name: "Chou-fleur" },
  { name: "Cidre" },
  { name: "Cidre brut" },
  { name: "Cidre doux" },
  { name: "Ciboulette" },
  { name: "Civet de lièvre" },
  { name: "Coca" },
  { name: "Cochon de lait" },
  { name: "Coco râpée" },
  { name: "Cognac" },
  { name: "Coing" },
  { name: "Cola" },
  { name: "Comté" },
  { name: "Concombre" },
  { name: "Coriandre" },
  { name: "Coulis de fruits rouges" },
  { name: "Coulis de tomate" },
  { name: "Couscous" },
  { name: "Courgette" },
  { name: "Courge butternut" },
  { name: "Courge spaghetti" },
  { name: "Cranberry" },
  { name: "Crème de cacao" },
  { name: "Crème de cassis" },
  { name: "Crème de menthe" },
  { name: "Crème fraîche" },
  { name: "Crêpe" },
  { name: "Cresson" },
  { name: "Crevette" },
  { name: "Croissant" },
  { name: "Crosne" },
  { name: "Cumin" },
  { name: "Curcuma" },
  { name: "Curry" },
  { name: "Curry rouge" },
  { name: "Curry vert" },
  { name: "Curry jaune" },
  { name: "Dinde" },
  { name: "Dorade" },
  { name: "Durian" },
  { name: "Edam" },
  { name: "Edamame" },
  { name: "Eau" },
  { name: "Eau de coco" },
  { name: "Eau minérale" },
  { name: "Eau pétillante" },
  { name: "Echalote" },
  { name: "Emmental" },
  { name: "Épinard" },
  { name: "Espadon" },
  { name: "Estragon" },
  { name: "Farine" },
  { name: "Farine de châtaigne" },
  { name: "Farine de maïs" },
  { name: "Farine de riz" },
  { name: "Fécule de maïs" },
  { name: "Fenouil" },
  { name: "Fenugrec" },
  { name: "Fève" },
  { name: "Figue" },
  { name: "Filet de cabillaud" },
  { name: "Filet de poulet" },
  { name: "Flocons d’avoine" },
  { name: "Focaccia" },
  { name: "Foie gras" },
  { name: "Framboise" },
  { name: "Fraise" },
  { name: "Fromage" },
  { name: "Fromage blanc" },
  { name: "Fruits confits" },
  { name: "Fruits de la passion" },
  { name: "Fruits rouges" },
  { name: "Fusilli" },
  { name: "Garam masala" },
  { name: "Genièvre" },
  { name: "Ghee" },
  { name: "Gingembre" },
  { name: "Gingembre confit" },
  { name: "Gingembre frais" },
  { name: "Gingembre moulu" },
  { name: "Gnocchi" },
  { name: "Goji" },
  { name: "Gouda" },
  { name: "Goyave" },
  { name: "Graines de courge" },
  { name: "Graines de lin" },
  { name: "Graines de tournesol" },
  { name: "Grana Padano" },
  { name: "Grenade" },
  { name: "Grisette" },
  { name: "Gruyère" },
  { name: "Guacamole" },
  { name: "Hareng" },
  { name: "Haricot blanc" },
  { name: "Haricot noir" },
  { name: "Haricot rouge" },
  { name: "Haricots verts" },
  { name: "Herbes de Provence" },
  { name: "Huile d'arachide" },
  { name: "Huile d'avocat" },
  { name: "Huile d'olive" },
  { name: "Huile de coco" },
  { name: "Huile de colza" },
  { name: "Huile de noisette" },
  { name: "Huile de pépins de raisin" },
  { name: "Huile de sésame" },
  { name: "Huile de tournesol" },
  { name: "Huîtres" },
  { name: "Jackfruit" },
  { name: "Jambon" },
  { name: "Jambon de parme" },
  { name: "Jaune d'œuf" },
  { name: "Jus d'ananas" },
  { name: "Jus d'orange" },
  { name: "Jus de citron" },
  { name: "Jus de cranberry" },
  { name: "Jus de goyave" },
  { name: "Jus de grenade" },
  { name: "Jus de pamplemousse" },
  { name: "Jus de pomme" },
  { name: "Jus de raisin" },
  { name: "Jus de tomate" },
  { name: "Kaki" },
  { name: "Kale" },
  { name: "Ketchup" },
  { name: "Kéfir" },
  { name: "Kiwi" },
  { name: "Kombucha" },
  { name: "Lait" },
  { name: "Lait d'amande" },
  { name: "Lait de coco" },
  { name: "Lait de noisette" },
  { name: "Lait de riz" },
  { name: "Lait de soja" },
  { name: "Laitue" },
  { name: "Lardons" },
  { name: "Laurier" },
  { name: "Lentille corail" },
  { name: "Lentille verte" },
  { name: "Levure chimique" },
  { name: "Levure de bière" },
  { name: "Levure de boulanger" },
  { name: "Lime" },
  { name: "Liqueur d'abricot" },
  { name: "Liqueur d'orange" },
  { name: "Liqueur de cassis" },
  { name: "Litchi" },
  { name: "Maïs" },
  { name: "Macédoine" },
  { name: "Madeleine" },
  { name: "Magret de canard" },
  { name: "Mangue" },
  { name: "Maracuja" },
  { name: "Marjolaine" },
  { name: "Martini" },
  { name: "Mascarpone" },
  { name: "Masala" },
  { name: "Mélasse" },
  { name: "Melon" },
  { name: "Menthe" },
  { name: "Merlan" },
  { name: "Merlu" },
  { name: "Mesclun" },
  { name: "Miel" },
  { name: "Mimolette" },
  { name: "Miso" },
  { name: "Moelleux au chocolat" },
  { name: "Morue" },
  { name: "Mortadelle" },
  { name: "Moutarde" },
  { name: "Mozzarella" },
  { name: "Muesli" },
  { name: "Mûre" },
  { name: "Muscade" },
  { name: "Myrtille" },
  { name: "Navet" },
  { name: "Nectar de mangue" },
  { name: "Nectarine" },
  { name: "Noisette" },
  { name: "Noix" },
  { name: "Noix de cajou" },
  { name: "Noix de coco" },
  { name: "Noix de pécan" },
  { name: "Noix du Brésil" },
  { name: "Nutella" },
  { name: "Oeuf" },
  { name: "Oignon" },
  { name: "Oignon rouge" },
  { name: "Olive noire" },
  { name: "Olive verte" },
  { name: "Orange" },
  { name: "Orge" },
  { name: "Origan" },
  { name: "Pain au levain" },
  { name: "Pain blanc" },
  { name: "Pain complet" },
  { name: "Pain de mie" },
  { name: "Pain pita" },
  { name: "Pain aux céréales" },
  { name: "Pain aux noix" },
  { name: "Pain burger" },
  { name: "Pamplemousse" },
  { name: "Papaye" },
  { name: "Paprika" },
  { name: "Parmesan" },
  { name: "Pâte brisée" },
  { name: "Pâte feuilletée" },
  { name: "Pâte filo" },
  { name: "Pâte sablée" },
  { name: "Pâtes" },
  { name: "Pâtes complètes" },
  { name: "Pâtes fraîches" },
  { name: "Pâtes sans gluten" },
  { name: "Patate douce" },
  { name: "Pavé de saumon" },
  { name: "Pêche" },
  { name: "Pecorino" },
  { name: "Pétoncle" },
  { name: "Piment d'Espelette" },
  { name: "Piment doux" },
  { name: "Piment fort" },
  { name: "Piment jalapeño" },
  { name: "Piment oiseau" },
  { name: "Pina colada" },
  { name: "Pineau des Charentes" },
  { name: "Pistache" },
  { name: "Pita" },
  { name: "Pizzas" },
  { name: "Poire" },
  { name: "Poireau" },
  { name: "Pois cassés" },
  { name: "Pois chiche" },
  { name: "Poisson blanc" },
  { name: "Poivre blanc" },
  { name: "Poivre gris" },
  { name: "Poivre noir" },
  { name: "Poivron jaune" },
  { name: "Poivron rouge" },
  { name: "Poivron vert" },
  { name: "Pomme" },
  { name: "Pomme de terre" },
  { name: "Porc" },
  { name: "Porto" },
  { name: "Pousses d'épinard" },
  { name: "Pousses de soja" },
  { name: "Poutargue" },
  { name: "Poulet" },
  { name: "Praliné" },
  { name: "Prune" },
  { name: "Purée de tomate" },
  { name: "Quinoa" },
  { name: "Radis" },
  { name: "Raisin" },
  { name: "Raisin sec" },
  { name: "Râpé végétal" },
  { name: "Ravioli" },
  { name: "Rhum" },
  { name: "Ricotta" },
  { name: "Riz" },
  { name: "Riz basmati" },
  { name: "Riz complet" },
  { name: "Riz gluant" },
  { name: "Riz jasmin" },
  { name: "Riz rond" },
  { name: "Roquefort" },
  { name: "Roquette" },
  { name: "Rose" },
  { name: "Rôti de porc" },
  { name: "Rôti de veau" },
  { name: "Rutabaga" },
  { name: "Rye" },
  { name: "Saké" },
  { name: "Salade" },
  { name: "Salami" },
  { name: "Salsifis" },
  { name: "Sardine" },
  { name: "Saucisse" },
  { name: "Saucisse de Toulouse" },
  { name: "Saucisson" },
  { name: "Saumon" },
  { name: "Saumon fumé" },
  { name: "Seigle" },
  { name: "Sel" },
  { name: "Semoule" },
  { name: "Sésame" },
  { name: "Sirop d'agave" },
  { name: "Sirop d'érable" },
  { name: "Sirop d'orgeat" },
  { name: "Sirop de grenadine" },
  { name: "Sirop de menthe" },
  { name: "Sirop de sucre" },
  { name: "Soba" },
  { name: "Soda" },
  { name: "Soja" },
  { name: "Sorbet" },
  { name: "Soupe miso" },
  { name: "Spaghetti" },
  { name: "Spéculoos" },
  { name: "Stilton" },
  { name: "Stracciatella" },
  { name: "Sucre" },
  { name: "Sucre glace" },
  { name: "Sucre roux" },
  { name: "Sucrine" },
  { name: "Tabasco" },
  { name: "Tahini" },
  { name: "Tamarin" },
  { name: "Tapioca" },
  { name: "Tartare" },
  { name: "Tequila" },
  { name: "Thon" },
  { name: "Thon en boîte" },
  { name: "Thym" },
  { name: "Thé" },
  { name: "Thé glacé" },
  { name: "Tiramisu" },
  { name: "Tofu" },
  { name: "Tomme" },
  { name: "Tomate" },
  { name: "Tomate cerise" },
  { name: "Tomate séchée" },
  { name: "Tonic" },
  { name: "Tortellini" },
  { name: "Tranche de bacon" },
  { name: "Truffe" },
  { name: "Truite" },
  { name: "Turmeric" },
  { name: "Vanille" },
  { name: "Veau" },
  { name: "Vegetable oil" },
  { name: "Velouté" },
  { name: "Vermicelle" },
  { name: "Vermouth" },
  { name: "Viande hachée" },
  { name: "Vinaigre balsamique" },
  { name: "Vinaigre blanc" },
  { name: "Vinaigre de cidre" },
  { name: "Vinaigre de riz" },
  { name: "Vinaigre de vin" },
  { name: "Vin blanc" },
  { name: "Vin doux naturel" },
  { name: "Vin rosé" },
  { name: "Vin rouge" },
  { name: "Vodka" },
  { name: "Wasabi" },
  { name: "Waterzoï" },
  { name: "Whisky" },
  { name: "Wok sauce" },
  { name: "Yaourt" },
  { name: "Yaourt grec" },
  { name: "Yuzu" },
  { name: "Zaatar" },
  { name: "Zucchini" },
];
