export const ustensils = [
  { name: "Autocuiseur" },
  { name: "Balance" },
  { name: "Batteur électrique" },
  { name: "Blender" },
  { name: "Bol" },
  { name: "Bouilloire" },
  { name: "Casserole" },
  { name: "Chinois" },
  { name: "Ciseau de cuisine" },
  { name: "Cocotte" },
  { name: "Corne de pâtissier" },
  { name: "Couteau" },
  { name: "Cuillère" },
  { name: "Cuillère à café" },
  { name: "Cuillère à soupe" },
  { name: "Cuiseur vapeur" },
  { name: "Entonnoir" },
  { name: "Faitout" },
  { name: "Fouet" },
  { name: "Fourchette" },
  { name: "Gant de cuisine" },
  { name: "Grille" },
  { name: "Louche" },
  { name: "Manique" },
  { name: "Maryse" },
  { name: "Microplane" },
  { name: "Mixeur" },
  { name: "Mortier" },
  { name: "Moule à cake" },
  { name: "Moule à gâteau" },
  { name: "Moule à tarte" },
  { name: "Passoire" },
  { name: "Pilons" },
  { name: "Pince de cuisine" },
  { name: "Planche à découper" },
  { name: "Plaque de cuisson" },
  { name: "Plat allant au four" },
  { name: "Poche à douille" },
  { name: "Poêle" },
  { name: "Presse-agrumes" },
  { name: "Presse-ail" },
  { name: "Presse-purée" },
  { name: "Robot de cuisine" },
  { name: "Râpe" },
  { name: "Saladier" },
  { name: "Sauteuse" },
  { name: "Spatule" },
  { name: "Tamis" },
  { name: "Thermomètre de cuisine" },
  { name: "Torchon" },
  { name: "Verre doseur" },
  { name: "Wok" },
  { name: "Zesteur" },
  { name: "Écumoire" }
];